version: "3.8"

services:
  # 1. Grafana (The Dashboard)
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3001:3000" # 3001 on host to avoid conflict with app on 3000
    volumes:
      - grafana-data:/var/lib/grafana

  # 2. Loki (The Log Collector)
  loki:
    image: grafana/loki:latest
    container_name: loki
    ports:
      - "3100:3100" # Loki's API port

  # 3. Prometheus (The Metrics Collector)
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml # Mount our config file
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"

  promtail:
    image: grafana/promtail:latest
    container_name: promtail
    volumes:
      # Mount config file
      - ./promtail-config.yml:/etc/promtail/config.yml
      # Mount app's log directory into the container
      - ./logs:/var/logs
    command:
      - -config.file=/etc/promtail/config.yml

volumes:
  grafana-data:
